# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True, verbose_name='关键词')),
                ('enable', models.IntegerField(default=1, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'keywords',
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='LoginInFo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('enable', models.IntegerField(default=1, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'login_info',
                'verbose_name': '微博登陆账号',
                'verbose_name_plural': '微博登陆账号',
            },
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='用户ID')),
                ('is_crawled', models.IntegerField(default=0, verbose_name='是否已采集个人信息')),
                ('other_crawled', models.IntegerField(default=0, verbose_name='是否已采集粉丝和关注')),
                ('home_crawled', models.IntegerField(default=0, verbose_name='是否已采集主页')),
            ],
            options={
                'db_table': 'seed_ids',
                'verbose_name': '要采集的账号',
                'verbose_name_plural': '要采集的账号',
            },
        ),
    ]
